# Build on macOS with Xcode 9.1
os: osx
osx_image: xcode9.1

# Configure caching
cache:
  timeout: 300000 # 5 minutes
  directories:
    - $HOME/src

# Define our build stages
jobs:
  include:
    - stage: Build
      install:
        - wget "https://github.com/Dids/Build_Clover/raw/master/Build_Clover.command"
        - chmod +x Build_Clover.command
        - cp -f "${TRAVIS_BUILD_DIR}/BuildCloverConfig.txt" "${HOME}/BuildCloverConfig.txt"
        - sed -i -e "s/.*SUGGESTED_CLOVER_REV.*/SUGGESTED_CLOVER_REV=${CLOVER_REVISION}/" "${HOME}/BuildCloverConfig.txt"
      script:
        - ./Build_Clover.command
    - stage: GitHub Release
      if: branch = master
      script: source .scripts/deploy.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: $HOME/src/edk2/Clover/CloverPackage/sym/Clover_*
        skip_cleanup: true
        name: "${GIT_TAG}"
        body: "${GIT_TAG_MSG}"
        on:
          tags: false
          branch: master

# Only build on specific branches
branches:
  only:
    - master
    - development
