# Build on macOS with Xcode 9.1
os: osx
osx_image: xcode9.1

# Configure caching
cache:
  timeout: 300000 # 5 minutes
  directories:
    - $HOME/src

# Define our build stages
jobs:
  include:
    - stage: Build
      install:
        - wget "https://github.com/Dids/Build_Clover/raw/master/Build_Clover.command"
        - chmod +x Build_Clover.command
        - ln -sf "${TRAVIS_BUILD_DIR}/BuildCloverConfig.txt" "${HOME}/BuildCloverConfig.txt"
      script:
        - ./Build_Clover.command
      after_success:
        ## TODO: Rewrite this once it's confirmed working
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export CLOVER_PKG_NAME=$(echo -n $HOME/src/edk2/Clover/CloverPackage/sym/Clover_*.pkg)
        - export CLOVER_PKG_NAME=$(basename ${CLOVER_PKG_NAME})
        - export CLOVER_PKG_NAME=$(echo -n ${CLOVER_PKG_NAME/.pkg/})
        - export GIT_TAG=$(echo -n ${CLOVER_PKG_NAME/Clover_/})
        - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
        - git push -q https://$GITHUB_OAUTH_TOKEN@github.com/Dids/clover-builder --tags
    ## TODO: We still need to detect the current version (eg. v2.4k_r4278)
    ##       and add it as a tag etc.
    - stage: GitHub Release
      #if: branch = master
      script: echo "Deploying to GitHub Releases.."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: $HOME/src/edk2/Clover/CloverPackage/sym/Clover_*
        skip_cleanup: true
        on:
          tags: false
          #branch: master
          all_branches: true ## TODO: Disable this and enable the two liens above once everything is working

# Build stage ordering
stages:
  - Build
  - name: GitHub Release
    if: branch = master

# Only build on specific branches
branches:
  only:
    - master
    - development
    #- /^v\d+(\.\d+)+$/