# Build on macOS with Xcode 9.1
os: osx
osx_image: xcode9.1

# Define our build stages
jobs:
  include:
    - stage: compile
      install:
        - wget "https://github.com/Dids/Build_Clover/raw/master/Build_Clover.command"
        - chmod +x Build_Clover.command
      script:
        - ./Build_Clover.command --cfg "${TRAVIS_BUILD_DIR}"
    - stage: deploy
      script: skip
      deploy: github
        ## TODO: Implement

# Build stage ordering
stages:
  - build
  - name: deploy
    if: branch = master

# Only build on specific branches
branches:
  only:
    - master
    - development