# Build on macOS with Xcode 9.1
os: osx
osx_image: xcode9.1

# Configure caching
cache:
  timeout: 300000 # 5 minutes
  directories:
    - $HOME/src

# Define our build stages
jobs:
  include:
    - stage: Build
      install:
        - wget "https://github.com/Dids/Build_Clover/raw/master/Build_Clover.command"
        - chmod +x Build_Clover.command
        - cp -f "${TRAVIS_BUILD_DIR}/BuildCloverConfig.txt" "${HOME}/BuildCloverConfig.txt"
        - sed -i -e "s/.*SUGGESTED_CLOVER_REV.*/SUGGESTED_CLOVER_REV=${CLOVER_REVISION}/" "${HOME}/BuildCloverConfig.txt"
      script:
        - ./Build_Clover.command
    - stage: GitHub Release
      if: branch = master
      script: .scripts/deploy.sh
      before_deploy:
        - export CLOVER_PKG_NAME=$(echo -n $HOME/src/edk2/Clover/CloverPackage/sym/Clover_*.pkg)
        - export CLOVER_PKG_NAME=$(basename ${CLOVER_PKG_NAME})
        - export CLOVER_PKG_NAME=$(echo -n ${CLOVER_PKG_NAME/.pkg/})
        - export GIT_TAG=$(echo -n ${CLOVER_PKG_NAME/Clover_/})
        - "export CLOVER_REVISION=$(cd $HOME/src/edk2/Clover && svn info | grep 'Revision: ' | tr -d 'Revision: ')"
        - export GIT_TAG_MSG=$(svn log svn://svn.code.sf.net/p/cloverefiboot/code --revision $CLOVER_REVISION --xml)
        - export GIT_TAG_MSG=$(echo $GIT_TAG_MSG | xmllint --xpath "string(//msg)" -)
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        title: $GIT_TAG
        body: $GIT_TAG_MSG
        file_glob: true
        file: $HOME/src/edk2/Clover/CloverPackage/sym/Clover_*
        skip_cleanup: true
        on:
          tags: false
          branch: master
          condition: $TRAVIS_PULL_REQUEST = false

# Only build on specific branches
branches:
  only:
    - master
    - development
